modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/SamsTheNerd/PotionIcons/issues"
license = "LGPL-3.0"
showAsResourcePack = false

[[mods]]
modId = "potionicons"
version = "${mod_version}"
displayName = "Potion Icons"
authors = "samsthenerd"
description = 'Putting effect icons in more places.'
logoFile = "assets/potionicons/icon.png"

[[dependencies.potionicons]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.potionicons]]
modId = "minecraft"
mandatory=true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.potionicons]]
modId = "inline"
mandatory=true
versionRange = "[1.20.1-1.2.2,)"
ordering = "NONE"
side = "BOTH"