modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/SamsTheNerd/PotionIcons/issues"
license = "LGPL-3.0"

[[mods]]
modId = "potionicons"
version = "${version}"
displayName = "Potion Icons"
authors = "samsthenerd"
description = '''
Putting effect icons in more places.
'''
logoFile = "assets/potionicons/icon.png"

[[dependencies.potionicons]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potionicons]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.potionicons]]
modId = "inline"
type = "required"
versionRange = "[1.21.1-1.2.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "potionicons.mixins.json"
